; ===================================================================
; RDPWrangler Server Connections & Settings INI File
; Passwords are securely encrypted via Windows DPAPI (PasswordEncrypted).
; ===================================================================

[Settings]
SplitterDistance=345
SidebarCollapsed=False
LastConnectedServerId=sample_dev
WindowWidth=2576
WindowHeight=1408
WindowMaximized=True

